#!/bin/bash

## ICA: Independente Component Analysis

## This will perform Independent Component Analysis. The output is a series of links which will be used to decide which components are artefacts. Components which contain unwanted artifacts will later be 'rejected' and one should keep a list of these the text file generated by the makereject function on matlab. We will also create a background image which is based off of an MNI image. This will fascilitate visual inspection of the ICAs. 

source preproc_config.sh

FSLDIR=/home/mpib/LNDG/FSL/fsl-5.0.11

# PBS Log Info
CurrentPreproc="ICA"
CurrentLog="${LogPath}/${CurrentPreproc}"
if [ ! -d ${CurrentLog} ]; then mkdir ${CurrentLog}; chmod 770 ${CurrentLog}; fi

# Error log
Error_Log="${CurrentLog}/${CurrentPreproc}_error_summary.txt"; echo "" >> ${Error_Log}; chmod 770 ${CurrentLog}

# Loop over participants, sessions (if they exist) & runs/conditions/tasks/etc
for SUB in ${SubjectID} ; do
		for RUN in ${RunID}; do
			
			# Name of functional image.
			FuncImage="${SUB}_run${RUN}_feat_detrended_highpassed"
			
			# Name of anatomical images to be used.
			AnatImage="${SUB}_anat_brain"	# Brain extracted anatomical image
			
			# Path to the anatomical and functional image folders.
			AnatPath="${DataPath}/${SUB}/anat/ANTs"					# Path for anatomical image
			FuncPath="${DataPath}/${SUB}/func/run${RUN}"
			
			if [ ! -f ${FuncPath}/${FuncImage}.nii.gz ]; then
				echo "No functional image found for ${SUB} run ${RUN}"
				continue
			elif [ -d ${FuncPath}/FEAT.feat/filtered_func_data.ica ]; then
				cd ${FuncPath}/FEAT.feat/filtered_func_data.ica
				Log=`grep "finished\!" log.txt | tail -1` # Get line containing our desired text output
				if [ ! ${Log} == "finished!" ]; then
					echo "${SUB} ${TASK} ${RUN}: ICA was incomplete, deleting and re-running"
					rm -rf ${FuncPath}/FEAT.feat/filtered_func_data.ica
					cd ${FuncPath} 		# Job file can't be created in a non-existing folder
				else
					echo "${SUB} ${TASK} ${RUN}: ICA was already run. Skipping subject/run."
					continue
				fi
			fi
			
			# Variables for background image and ICA
			Preproc="${FuncPath}/${FuncImage}.nii.gz"							# Preprocessed data image
			BET="${AnatPath}/${AnatImage}.nii.gz"											# Brain extracted T1 image
			ANAT2FUNC="${FuncPath}/FEAT.feat/anat2func.nii.gz"										# Background image for ICA
			ICA="${FuncPath}/FEAT.feat/filtered_func_data.ica"								# Location for ICA 
			Report="${FuncPath}/FEAT.feat/filtered_func_data.ica/report.html"				# Location for ICA report links
			
			# Gridwise
			echo "#!/bin/bash" 	>> job # Interpreter
			echo "#SBATCH --job-name ${CurrentPreproc}_${SUB}_run${RUN}" 	>> job # Job name 
			echo "#SBATCH --time 4:00:00" 						>> job # Time until job is killed 
			echo "#SBATCH --mem 4GB" 								>> job # Books 10gb RAM for the job 
			echo "#SBATCH --mail-type NONE" 										>> job # Email notification on abort/end, use 'n' for no notification 
			echo "#SBATCH --output ${CurrentLog}/slurm-%j.out" 							>> job # Write output log to group log folder
			echo "#SBATCH --workdir ${WorkingDirectory}" 							>> job # working directory

			# Initialize FSL 	
			echo "FSLDIR=/home/mpib/LNDG/FSL/fsl-5.0.11"  >> job
			echo ". ${FSLDIR}/etc/fslconf/fsl.sh"                   >> job
			echo "PATH=${FSLDIR}/bin:${PATH}"                       >> job
			echo "export FSLDIR PATH"                               >> job
			
			echo "tmpnam /home/mpib/LNDG/fsl_temp/fsl" 						>> job # change fsl temp folder
			
			## Run ICA commands
		
			# Create a condition specific background image to facilitate component rejection. Made by registering MNI image to functional image.
			if [ ! -f ${ANAT2FUNC} ]; then
				echo "flirt -in ${BET} -ref ${Preproc} -applyxfm -init ${FuncPath}/FEAT.feat/reg/highres2example_func.mat -out ${ANAT2FUNC}" 								>> job
			fi
			
			# Perform ICA			
			echo -n "melodic -i ${Preproc} -o ${ICA} --dimest=${dimestVALUE} -d ${dimensionalityVALUE} " 		>> job
			echo -n "--tr=${TR} --report --guireport=${Report} --nobet --bgthreshold=${bgthresholdVALUE} " 		>> job
			echo "--mmthresh=${mmthreshVALUE} --bgimage=${ANAT2FUNC} ${AdditionalParameters}" 					>> job
			
			# Error Log
			echo "cd ${FuncPath}/FEAT.feat/filtered_func_data.ica" 												>> job
			echo "Log=\`grep \"finished!\" log.txt | tail -1\`" 												>> job
			echo "if [ ! \"\$Log\" == \"finished!\" ]; then echo 'Error in ${FuncImage}' >> ${Error_Log}; fi"	>> job
			
			sbatch job
			rm job
			
		done
done
